### ISSUE TITLE
Bug in get_default_genotypes() of propose_genotypes.py

### ISSUE THREAD

**Issue by lam-ian** [maxwshen/evoracle#1]
Hello, I am currently reading the Evoracle paper for journal club and was looking at the `propose_genotypes.py` code to understand how that step is done. I noticed that the sorting in the following line might have a bug. 
https://github.com/maxwshen/evoracle/blob/4bee871d2c65c8ac0f378fcf00fb1e89205640cf/propose_genotypes.py#L174

The `col` variable is of type `string`, not `int`, so when the sorting is done (using the Cry1Ac 100nt obs as example), 
the timepoints became ['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '22', '24', '26', '28', '3', '30', '32', '34', '36', '38', '4', '40', '42', '44', '46', '5', '6', '7', '8', '9'], instead of  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46].  

According to the Methods of the paper, you would like to look at the change rates between consecutive timepoints. I am not sure how much of an issue this will create for downstream, since the differences are calculated based on T10 - T1, T20 - T2, etc, instead of T10 - T9, T20 - T19, etc...

Hope this helps. Thank you very much!

**Comment by maxwshen** [comment]
Thank you for bringing this to my attention. Most of the timepoints are still consecutive after incorrect sorting, so the result would be some noise in the optimization. This bug has been fixed.
